config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home' # This is equivalent to

  match '/help', to: 'static_pages#help', via: 'get'
  get '/about', to: 'static_pages#about', via: 'get' # match & get is the same
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :users do
     member do
        get :following, :followers # URL: /users/45/following
     end
     collection do
        get :admins # URL: /users/admins
     end
  end

  resources :sessions, only: [:new, :create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!-- Goes on top of page.
     The class names starting with 'navbar', and also 'container', 'nav' and 'pull-right',
     have special meaning inside the Bootstrap framework.
-->
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "My playground application", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li class="dropdown" id="fat_menu">
                <%# data- attributes are ignored by the UA, but can be retrieved via JavaScript. It's understood by Bottstrap. %>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account for <%= current_user.name %><b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><%= link_to "User Profile", current_user %></li>
                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Run away!", signout_path, method: 'delete' %></li>
                </ul>
             </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- presence() is a method added by Rails to the String class -->
  <title>RoR FirstApp | <%= yield(:title).presence||'somewhere' %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
        <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <!-- Produces HTML code to show the argument in YAML format.
         It is wrapped in <pre class="debug_dump"></pre>
    -->
    <%= debug(params) if Rails.env.development? %>
</body>
</html>